# Generated by Django 4.2.5 on 2023-09-29 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_created_date_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rut',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.rol'),
        ),
    ]
