# Generated by Django 4.2.5 on 2023-10-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='abreviacion',
            field=models.CharField(default='GM', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoingrediente',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
