# Generated by Django 4.2.5 on 2023-10-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_producto_abreviacion_productoingrediente_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
