# Generated by Django 4.2.5 on 2023-10-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
