# Generated by Django 4.2.5 on 2023-10-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_pedido_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='restaurant.PedidoProducto', to='restaurant.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(through='restaurant.ProductoIngrediente', to='restaurant.ingrediente'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='precio_salida',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
