# Generated by Django 4.2.5 on 2023-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_estadopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(default='gr', max_length=16),
            preserve_default=False,
        ),
    ]
