# Generated by Django 4.2.5 on 2023-11-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_ajustestock_producto_ajustestock_ingrediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustestock',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad_critica',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad_disponible',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productoingrediente',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
